update scripts
update scripts

diff --git a/bin/clean-idea-projects b/bin/clean-idea-projects
--- a/bin/clean-idea-projects
+++ b/bin/clean-idea-projects
@@ -1,4 +1,13 @@
-#!/bin/sh
+#!/usr/bin/env bash
+if [[ -z "$1" ]]; then
+  echo "Error: Missing path"
+  echo
+  echo "Usage: `basename "$0"` <path>"
+  echo "       e.g. `basename "$0"` ."
+  echo
+  exit 1
+fi
+
 find "$1" -name \.idea -type d -print0 | xargs -0 rm -r
 find "$1" -name \*.iml -type f -delete
 find "$1" -name \*.iws -type f -delete
diff --git a/bin/git-remote-clone b/bin/git-remote-clone
--- a/bin/git-remote-clone
+++ b/bin/git-remote-clone
@@ -1,4 +1,11 @@
-#!/bin/sh
+#!/usr/bin/env bash
+if [[ ! "$1" || ! "$2" ]]; then
+  echo "Error! Bad arguments"
+  echo "Usage: $(basename "$0") <source_repo> <target_repo>"
+  echo
+  exit 1
+fi
+
 echo "Copying $1 ==> $2"
 mkdir temp
 cd temp
diff --git a/bin/git-rename-branch b/bin/git-rename-branch
--- a/bin/git-rename-branch
+++ b/bin/git-rename-branch
@@ -1,6 +1,13 @@
-#!/bin/sh
-git checkout $1                     # switch branch
-git pull                            # pull
-git branch -m $1 $2                 # rename local branch
-git push origin :$1                 # Delete the old branch
-git push --set-upstream origin $2   # Push the new branch, set local branch to track the new remote
+#!/usr/bin/env bash
+if [[ ! "$1" || ! "$2" ]]; then
+  echo "Error! Bad arguments"
+  echo "Usage: $(basename "$0") <branch> <new_name>"
+  echo
+  exit 1
+fi
+
+git checkout "$1"                     # switch branch
+git pull                              # pull
+git branch -m "$1" "$2"               # rename local branch
+git push origin ":$1"                 # Delete the old branch
+git push --set-upstream origin "$2"   # Push the new branch, set local branch to track the new remote
